site_name: 时光之赛博札记
site_description: 中文网络安全与科技信息归档
site_url: https://bytecapsule.github.io/sino-cyber-notes-site/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.top

plugins: []

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css
